resources:
  limits:
    cpus: 2.0
    memory: 4096

medusa:
  instance_name: My Medusa
  additional_envs: []
network:
  host_network: false
  web_port: 8080

run_as:
  user: 568
  group: 568

ix_volumes:
  medusa-config: /mnt/pool/medusa-config

ix_context:
  dev_mode: true

storage:
  config:
    type: ix_volume
    volume_name: medusa-config
    ix_volume_config:
      dataset_name: medusa-config
  additional_storage:
    - type: volume
      volume_name: my-series
      mount_path: /series
    - type: anonymous
      mount_path: /scratchpad
      volume_config:
        nocopy: true
    - type: host_path
      mount_path: /video
      auto_permissions: true
      host_path_config:
        path: /mnt/pool/video
    - type: host_path
      mount_path: /mnt/pool/video-acl
      auto_permissions: true
      host_path_config:
        acl_enable: true
        acl:
          path: /mnt/pool/video-acl
